---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: one-off-job
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/pascalva/gitops-test
      revision: main
      directories:
      - path: "examples/one-off-job/applications/*"
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: argocd
      labels:
        app: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/pascalva/gitops-test
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        name: in-cluster
        namespace: default
