---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-customer01
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: customers
  source:
    repoURL: https://github.com/pascalva/gitops-test
    path: examples/app-in-app/customer01/argocd
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
