---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer02
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  labels:
    customer: customer02
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/pascalva/gitops-test
      revision: main
      directories:
      - path: "examples/app-in-app/customer02/applications/*"
      - path: "examples/app-in-app/customer02/applications/static-app-*"
        exclude: true
  template:
    metadata:
      name: 'customer02-{{.path.basename}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
      labels:
        app: '{{.path.basename}}'
    spec:
      project: customers-customer02
      source:
        repoURL: https://github.com/pascalva/gitops-test
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        name: in-cluster
        namespace: customer02
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
  syncPolicy:
    preserveResourcesOnDeletion: true
  ignoreApplicationDifferences:
  - jsonPointers:
      - /metadata/finalizers
