---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer02-applicationset
  namespace: argocd
  labels:
    customer: customer02
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/PascalVA/gitops-test.git
      revision: main
      directories:
      - path: "examples/app-in-apps/customer02/applications/*"
      - path: "examples/app-in-apps/customer02/applications/static-app-*"
        exclude: true
  template:
    metadata:
      name: 'app-{{.path.basename}}'
      namespace: applications
      labels:
        app: '{{.path.basename}}'
    spec:
      project: applications
      source:
        repoURL: https://github.com/PascalVA/gitops-test.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
  syncPolicy:
    preserveResourcesOnDeletion: true
  ignoreApplicationDifferences:
  - jsonPointers:
      - /metadata/finalizers
