apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dynamic-2
  name: dynamic-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-2
  template:
    metadata:
      labels:
        app: dynamic-2
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        volumeMounts:
        - name: config-dynamic-2
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: config-dynamic-2
        configMap:
          name: dynamic-2
